package br.gov.ce.esp.pojos;
// Generated 14/10/2011 13:55:38 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Adm generated by hbm2java
 */
@Entity
@Table(name = "adm", schema = "monesp")
public class Adm implements java.io.Serializable {

    private int codigo;
    private String usuario;
    private String senha;
    private boolean flgadmin;

    public Adm() {
    }

    public Adm(String usuario, String senha, boolean flgadmin) {
        this.usuario = usuario;
        this.senha = senha;
        this.flgadmin = flgadmin;
    }

    public Adm(int codigo, String usuario, String senha, boolean flgadmin) {
        this.codigo = codigo;
        this.usuario = usuario;
        this.senha = senha;
        this.flgadmin = flgadmin;
    }

    @Id
    @Column(name = "codigo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "usuario", nullable = false, length = 50)
    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Column(name = "senha", nullable = false)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Column(name = "flgadmin", nullable = false)
    public boolean isFlgadmin() {
        return this.flgadmin;
    }

    public void setFlgadmin(boolean flgadmin) {
        this.flgadmin = flgadmin;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Adm other = (Adm) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + this.codigo;
        return hash;
    }
}
