package br.gov.ce.esp.pojos;
// Generated 25/08/2011 16:27:38 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Monografias generated by hbm2java
 */
@Entity
@Table(name = "monografias", schema = "monesp")
public class Monografias implements java.io.Serializable {

    private int codigo;
    private Linhaspesquisa linhaspesquisa;
    private Programas programas;
    private String tlptbr;
    private String tlpeng;
    private String autor;
    private String orientador;
    private String coorientador;
    private String bncex;
    private Date datadefesa;
    private String resumo;
    private String abstractresumo;
    private String caminho;

    public Monografias() {
    }

    public Monografias(String tlptbr, String tlpeng, String autor, String orientador, String coorientador, String bncex, Date datadefesa, String resumo, String abstractresumo, String caminho) {
        this.tlptbr = tlptbr;
        this.tlpeng = tlpeng;
        this.autor = autor;
        this.orientador = orientador;
        this.coorientador = coorientador;
        this.bncex = bncex;
        this.datadefesa = datadefesa;
        this.resumo = resumo;
        this.abstractresumo = abstractresumo;
        this.caminho = caminho;
    }

    public Monografias(int codigo, Linhaspesquisa linhaspesquisa, Programas programas, String tlptbr, String autor, String resumo, String abstractresumo) {
        this.codigo = codigo;
        this.linhaspesquisa = linhaspesquisa;
        this.programas = programas;
        this.tlptbr = tlptbr;
        this.autor = autor;
        this.resumo = resumo;
        this.abstractresumo = abstractresumo;
    }

    public Monografias(int codigo, Linhaspesquisa linhaspesquisa, Programas programas, String tlptbr, String tlpeng, String autor, String orientador, String coorientador, String bncex, Date datadefesa, String resumo, String abstractresumo, String caminho) {
        this.codigo = codigo;
        this.linhaspesquisa = linhaspesquisa;
        this.programas = programas;
        this.tlptbr = tlptbr;
        this.tlpeng = tlpeng;
        this.autor = autor;
        this.orientador = orientador;
        this.coorientador = coorientador;
        this.bncex = bncex;
        this.datadefesa = datadefesa;
        this.resumo = resumo;
        this.abstractresumo = abstractresumo;
        this.caminho = caminho;
    }

    public Monografias(Linhaspesquisa linhaspesquisa, Programas programas, String tlptbr, String tlpeng, String autor, String orientador, String coorientador, String bncex, Date datadefesa, String resumo, String abstractresumo, String caminho) {
        this.linhaspesquisa = linhaspesquisa;
        this.programas = programas;
        this.tlptbr = tlptbr;
        this.tlpeng = tlpeng;
        this.autor = autor;
        this.orientador = orientador;
        this.coorientador = coorientador;
        this.bncex = bncex;
        this.datadefesa = datadefesa;
        this.resumo = resumo;
        this.abstractresumo = abstractresumo;
        this.caminho = caminho;
    }

    @Id
    @Column(name = "codigo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fkcodpesquisa", nullable = false)
    public Linhaspesquisa getLinhaspesquisa() {
        return this.linhaspesquisa;
    }

    public void setLinhaspesquisa(Linhaspesquisa linhaspesquisa) {
        this.linhaspesquisa = linhaspesquisa;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fkcodprograma", nullable = false)
    public Programas getProgramas() {
        return this.programas;
    }

    public void setProgramas(Programas programas) {
        this.programas = programas;
    }

    @Column(name = "tlptbr", nullable = false, length = 200)
    public String getTlptbr() {
        return this.tlptbr;
    }

    public void setTlptbr(String tlptbr) {
        this.tlptbr = tlptbr;
    }

    @Column(name = "tlpeng", length = 200)
    public String getTlpeng() {
        return this.tlpeng;
    }

    public void setTlpeng(String tlpeng) {
        this.tlpeng = tlpeng;
    }

    @Column(name = "autor", nullable = false, length = 100)
    public String getAutor() {
        return this.autor;
    }

    public void setAutor(String autor) {
        this.autor = autor;
    }

    @Column(name = "orientador", length = 100)
    public String getOrientador() {
        return this.orientador;
    }

    public void setOrientador(String orientador) {
        this.orientador = orientador;
    }

    @Column(name = "coorientador", length = 100)
    public String getCoorientador() {
        return this.coorientador;
    }

    public void setCoorientador(String coorientador) {
        this.coorientador = coorientador;
    }

    @Column(name = "bncex", length = 500)
    public String getBncex() {
        return this.bncex;
    }

    public void setBncex(String bncex) {
        this.bncex = bncex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datadefesa", length = 13)
    public Date getDatadefesa() {
        return this.datadefesa;
    }

    public void setDatadefesa(Date datadefesa) {
        this.datadefesa = datadefesa;
    }

    @Column(name = "resumo", nullable = false, length = 1500)
    public String getResumo() {
        return this.resumo;
    }

    public void setResumo(String resumo) {
        this.resumo = resumo;
    }

    @Column(name = "abstractresumo", nullable = false, length = 1500)
    public String getAbstractresumo() {
        return this.abstractresumo;
    }

    public void setAbstractresumo(String abstractresumo) {
        this.abstractresumo = abstractresumo;
    }

    @Column(name = "caminho", length = 200)
    public String getCaminho() {
        return this.caminho;
    }

    public void setCaminho(String caminho) {
        this.caminho = caminho;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Monografias other = (Monografias) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + this.codigo;
        return hash;
    }
}
