package br.gov.ce.esp.pojos;
// Generated 25/08/2011 16:27:38 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programas generated by hbm2java
 */
@Entity
@Table(name = "programas", schema = "monesp")
public class Programas implements java.io.Serializable {

    private int codigo;
    private String nomeprograma;
    private Set<Monografias> monografiases = new HashSet<Monografias>(0);

    public Programas() {
    }

    public Programas(String nomeprograma) {
        this.nomeprograma = nomeprograma;
    }

    public Programas(int codigo, String nomeprograma) {
        this.codigo = codigo;
        this.nomeprograma = nomeprograma;
    }

    public Programas(int codigo, String nomeprograma, Set<Monografias> monografiases) {
        this.codigo = codigo;
        this.nomeprograma = nomeprograma;
        this.monografiases = monografiases;
    }

    @Id
    @Column(name = "codigo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nomeprograma", nullable = false, length = 100)
    public String getNomeprograma() {
        return this.nomeprograma;
    }

    public void setNomeprograma(String nomeprograma) {
        this.nomeprograma = nomeprograma;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "programas")
    public Set<Monografias> getMonografiases() {
        return this.monografiases;
    }

    public void setMonografiases(Set<Monografias> monografiases) {
        this.monografiases = monografiases;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Programas other = (Programas) obj;
        if (this.codigo != other.codigo) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + this.codigo;
        return hash;
    }
}
